from enum import Enum

UPLOAD_DIR = "uploads"

MSG_SEEN_STATUS_USER = 'user'
MSG_SEEN_STATUS_TIMESTAMP = 'ts'

MSG_SEEN_STATUS_GRP_CODE = 'msg_seen_status'
MSG_SEEN_STATUS_GRP_ID = 1
MSG_PENDING_STATUS = 1
MSG_SEEN_STATUS = 2
MSG_SENT_STATUS = 3

MESSAGE_OFFSET = 0
MESSAGE_LIMIT = 1000

PREFIX_LENGTH_OF_DOCUMENT = 36 + 7 + 1 + 1
# PREFIX_LENGTH_OF_DOCUMENT = uuid  +  folder_path  +  1 \  +  1 _
TOPIC_MESSAGE_SENT = 'message_sent'
TOPIC_CHAT_SEEN = 'chat_seen'
