"""empty message

Revision ID: 0b3491b128c0
Revises: 763c9aa591b5
Create Date: 2025-03-12 00:46:36.687430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0b3491b128c0'
down_revision: Union[str, None] = '763c9aa591b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('created_on', sa.TIMESTAMP(), nullable=True))
    op.drop_constraint('message_ibfk_6', 'message', type_='foreignkey')
    op.drop_constraint('message_ibfk_3', 'message', type_='foreignkey')
    op.drop_column('message', 'status_id')
    op.drop_column('message', 'message_type_id')
    op.add_column('message_seen_status', sa.Column('is_current', sa.Boolean(), nullable=True))
    op.add_column('message_seen_status', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('message_seen_status', sa.Column('updated_on', sa.TIMESTAMP(), nullable=True))
    op.create_foreign_key(None, 'message_seen_status', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message_seen_status', type_='foreignkey')
    op.drop_column('message_seen_status', 'updated_on')
    op.drop_column('message_seen_status', 'user_id')
    op.drop_column('message_seen_status', 'is_current')
    op.add_column('message', sa.Column('message_type_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('message', sa.Column('status_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('message_ibfk_3', 'message', 'constant', ['message_type_id'], ['id'])
    op.create_foreign_key('message_ibfk_6', 'message', 'constant', ['status_id'], ['id'])
    op.drop_column('message', 'created_on')
    # ### end Alembic commands ###
