"""empty message

Revision ID: 174f59853f2e
Revises: 8fab28e47b14
Create Date: 2025-03-09 01:58:00.687494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '174f59853f2e'
down_revision: Union[str, None] = '8fab28e47b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('is_group_chat', sa.Boolean(), nullable=False))
    op.alter_column('user', 'is_logged_in',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_logged_in',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('chat', 'is_group_chat')
    # ### end Alembic commands ###
