"""empty message

Revision ID: 3fcf4e603854
Revises: 0b3491b128c0
Create Date: 2025-03-12 01:10:24.585500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3fcf4e603854'
down_revision: Union[str, None] = '0b3491b128c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'message_timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('message_timestamp', mysql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###
