"""empty message

Revision ID: 49f05bb6e6a3
Revises: 7d8ba7790e30
Create Date: 2025-06-02 22:34:04.780338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '49f05bb6e6a3'
down_revision: Union[str, None] = '7d8ba7790e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('parent_message_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_message_parent_message_id'), 'message', ['parent_message_id'], unique=False)
    op.drop_constraint('message_ibfk_7', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'message', ['parent_message_id'], ['id'])
    op.drop_column('message', 'thread_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('thread_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_ibfk_7', 'message', 'thread', ['thread_id'], ['id'])
    op.drop_index(op.f('ix_message_parent_message_id'), table_name='message')
    op.drop_column('message', 'parent_message_id')
    # ### end Alembic commands ###
