"""empty message

Revision ID: 4ae02f7f6789
Revises: a4e361be4c39
Create Date: 2025-02-28 00:45:31.875701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4ae02f7f6789'
down_revision: Union[str, None] = 'a4e361be4c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_logged_in', sa.Boolean(), nullable=True))
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'login_status_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login_status_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_ibfk_1', 'user', 'constant', ['login_status_id'], ['id'])
    op.drop_column('user', 'is_logged_in')
    # ### end Alembic commands ###
