"""empty message

Revision ID: 6248c4ae6e01
Revises: 3fcf4e603854
Create Date: 2025-03-13 00:07:44.516699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6248c4ae6e01'
down_revision: Union[str, None] = '3fcf4e603854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_user_map', sa.Column('last_seen_timestamp', sa.TIMESTAMP(), nullable=True))
    op.add_column('message_seen_status', sa.Column('seen_status', sa.JSON(), nullable=True))
    op.drop_constraint('message_seen_status_ibfk_3', 'message_seen_status', type_='foreignkey')
    op.drop_constraint('message_seen_status_ibfk_2', 'message_seen_status', type_='foreignkey')
    op.drop_column('message_seen_status', 'updated_on')
    op.drop_column('message_seen_status', 'user_id')
    op.drop_column('message_seen_status', 'is_current')
    op.drop_column('message_seen_status', 'sent_status_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_seen_status', sa.Column('sent_status_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('message_seen_status', sa.Column('is_current', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('message_seen_status', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('message_seen_status', sa.Column('updated_on', mysql.TIMESTAMP(), nullable=True))
    op.create_foreign_key('message_seen_status_ibfk_2', 'message_seen_status', 'constant', ['sent_status_id'], ['id'])
    op.create_foreign_key('message_seen_status_ibfk_3', 'message_seen_status', 'user', ['user_id'], ['id'])
    op.drop_column('message_seen_status', 'seen_status')
    op.drop_column('chat_user_map', 'last_seen_timestamp')
    # ### end Alembic commands ###
