"""empty message

Revision ID: 763c9aa591b5
Revises: 6e8e6f2947d3
Create Date: 2025-03-09 02:32:25.040855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '763c9aa591b5'
down_revision: Union[str, None] = '6e8e6f2947d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_ibfk_2', 'chat', type_='foreignkey')
    op.drop_column('chat', 'chat_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('chat_type_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('chat_ibfk_2', 'chat', 'constant', ['chat_type_id'], ['id'])
    # ### end Alembic commands ###
