"""empty message

Revision ID: 8deacf51da7b
Revises: 00bd44979aec
Create Date: 2025-04-26 00:16:47.788543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8deacf51da7b'
down_revision: Union[str, None] = '00bd44979aec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('code', table_name='constant')
    op.add_column('user', sa.Column('currently_opened_chat_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_ibfk_2', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'chat', ['currently_opened_chat_id'], ['id'])
    op.drop_column('user', 'theme_id')
    op.drop_column('user', 'last_opened_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_opened_date', mysql.TIMESTAMP(), nullable=True))
    op.add_column('user', sa.Column('theme_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_ibfk_2', 'user', 'constant', ['theme_id'], ['id'])
    op.drop_column('user', 'currently_opened_chat_id')
    op.create_index('code', 'constant', ['code'], unique=True)
    # ### end Alembic commands ###
